### ISSUE TITLE
Split get_catchment routine into two functions

### ISSUE THREAD

**Issue by dvignoles** [fabio1299/Visualization#7]
Currently the postgresql routine get_catchment recursively selects the "catchment table". It then aggregates all the geometry into one polygon and returns that. 

In order to maintain the subbasin information within the catchment, the recursive table select should be it's own function. With a get_catchment_geom function that leverages it.

**Comment by dvignoles** [comment]
See get_catchment_table routine.

Next Step: connect django model method to temporarily store result of get_catchment_table. From there we can pass the table into a get_catchment_geom function, while maintaining the original table in memory.

**Comment by dvignoles** [comment]
Updated setup calls get_catchment postgres routine to return table to python. From there osgeo is used to union to subbasin geometry efficiently through djangos GEOSGeometry library.

**Comment by fabio1299** [comment]
👍

On Nov 21, 2019, at 11:35 PM, Daniel Vignoles <notifications@github.com> wrote:

﻿

Updated setup calls get_catchment postgres routine to return table to python. From there osgeo is used to union to subbasin geometry efficiently through djangos GEOSGeometry library.
