### ISSUE TITLE
Create access point to other database schemas

### ISSUE THREAD

**Issue by dvignoles** [fabio1299/Visualization#8]
In order to access & aggregate the model statistics I need to access non public schemas through django. Utilizing dblink may be best approach?

**Comment by dvignoles** [comment]
https://stackoverflow.com/questions/31726064/how-to-connect-to-multiple-postgresql-schemas-from-django

Will try to first access schemas using db_table meta attribute.

**Comment by fabio1299** [comment]
Yes, DBlink seems to be the simplest (only ?) option to do that.
Unfortunately using DBlink greatly reduces the performance because of the limitations that the plugin has in terms of using indices...
Any workaround would be welcome, but I don’t know if such a workaround exists...


On Nov 21, 2019, at 11:39 PM, Daniel Vignoles <notifications@github.com> wrote:

﻿

In order to access & aggregate the model statistics I need to access non public schemas through django. Utilizing dblink may be best approach?

**Comment by dvignoles** [comment]
@fabio1299 One possibility that I think may work is setting up a [graphql](graphql.org) server as the entry point to all of our data. We could set up a [Hasura](https://github.com/hasura/graphql-engine) docker instance acting as a middle man for data requests. Based on the graphql queries we send, custom resolvers could access the different databases/schemas. At least I think so.

**Comment by dvignoles** [comment]
Based on [the docs](https://docs.hasura.io/1.0/graphql/manual/deployment/postgres-permissions.html) it seems like supporting multiple postgres schemas wouldn't be an issue.

**Comment by dvignoles** [comment]
I set up a test instance of Hasura. Basically each Hasura docker instance it tied to a specific database. Crucially, each instance **can** access and join across different schemas within the database. 

However, accessing other databases will require setting up separate graphql servers for each. Each of these separate API's can then be added to Hasura as "remote schemas." 

So a possible design would be:
* A Hasura instance for each database, providing access to all needed schema
* 1 Master Hasura Instance which stitches all the others together into one cohesive API

Check out "Use Case 3" in [this medium article](https://blog.hasura.io/remote-joins-a-graphql-api-to-join-database-and-other-data-sources/) to see what I mean.

**Comment by dvignoles** [comment]
Did some testing of querying different schema's via the graphql endpoint. It works nicely, but slows down if you try to draw data from multiple schemas in a single query. I think it will be faster to asynchronously make multiple small queries rather than one mega query. Next step is to figure out how that works with [asyncio](https://realpython.com/async-io-python/).
